# Generated by Django 4.2.16 on 2024-11-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_actuator_actuator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuatormember',
            name='index',
            field=models.CharField(max_length=50),
        ),
    ]
