# Generated by Django 4.2.16 on 2024-11-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_actuatormember_index'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actuatormember',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='actuatormember',
            name='parent',
        ),
    ]
